# Generated by Django 5.1 on 2024-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('name_of_wife', models.CharField(max_length=15)),
                ('no_of_child_below_5', models.IntegerField()),
                ('no_of_child_above_5', models.IntegerField()),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
